FROM apache/spark:3.5.8

USER root

ENV SPARK_JARS_DIR=/opt/spark/jars

RUN curl -fSL -o $SPARK_JARS_DIR/delta-spark_2.12-3.2.0.jar \
            https://repo1.maven.org/maven2/io/delta/delta-spark_2.12/3.2.0/delta-spark_2.12-3.2.0.jar && \
    curl -fSL -o $SPARK_JARS_DIR/delta-storage-3.2.0.jar \
            https://repo1.maven.org/maven2/io/delta/delta-storage/3.2.0/delta-storage-3.2.0.jar && \
    curl -fSL -o $SPARK_JARS_DIR/hadoop-aws-3.3.4.jar \
            https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar && \
    curl -fSL -o $SPARK_JARS_DIR/aws-java-sdk-bundle-1.12.262.jar \
            https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar && \
    curl -fSL -o $SPARK_JARS_DIR/spark-sql-kafka-0-10_2.12-3.5.1.jar \
            https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.5.1/spark-sql-kafka-0-10_2.12-3.5.1.jar && \
    curl -fSL -o $SPARK_JARS_DIR/kafka-clients-3.7.0.jar \
            https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.7.0/kafka-clients-3.7.0.jar && \
    curl -fSL -o $SPARK_JARS_DIR/spark-token-provider-kafka-0-10_2.12-3.5.1.jar \
            https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_2.12/3.5.1/spark-token-provider-kafka-0-10_2.12-3.5.1.jar && \
    curl -fSL -o $SPARK_JARS_DIR/commons-pool2-2.12.0.jar \
            https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.12.0/commons-pool2-2.12.0.jar


COPY requirements.txt /tmp/requirements.txt
RUN python3 -m pip install --no-cache-dir -r /tmp/requirements.txt && \
    python3 -c "import nltk; nltk.download('vader_lexicon', download_dir='/usr/share/nltk_data')"

ENV NLTK_DATA=/usr/share/nltk_data

COPY src/ /app/src/
COPY pyproject.toml /app/

ENV PYTHONPATH=/app

USER spark