# Here you can define all your datasets by using simple YAML syntax.
#
# Documentation for this file format can be found in "The Data Catalog"
# Link: https://docs.kedro.org/en/stable/data/data_catalog.html

# =============================================================================
# Parametros Globais
# =============================================================================
_common_environment: &environment_default
  environment: prd

_sql_common: &sql_common
  type: factory.datasets.AppendSQLDataset
  credentials: db_credentials
  batch_size: 500
  <<: *environment_default

# =============================================================================
# 00 - Governance
# =============================================================================

pipeline_logs:
  <<: *sql_common
  table_name: governance.pipeline_logs
  pk_columns: [run_id, entity_name]

validation_data_mercado:
  <<: *sql_common
  table_name: governance.validation_data_mercado
  pk_columns: [cod_indice, dat_ref]

validation_data_indicadores:
  <<: *sql_common
  table_name: governance.validation_data_indicadores
  pk_columns: [indicator, score_col, dat_ref]

validation_indice_isbm:
  <<: *sql_common
  table_name: governance.validation_indice_isbm
  pk_columns: [indicator, dat_ref]

metrics_stage_cds:
  <<: *sql_common
  table_name: governance.metrics_stage_cds
  pk_columns: [metrics_id]

metrics_stage_ibov:
  <<: *sql_common
  table_name: governance.metrics_stage_ibov
  pk_columns: [metrics_id]

metrics_stage_ivvb:
  <<: *sql_common
  table_name: governance.metrics_stage_ivvb
  pk_columns: [metrics_id]

metrics_stage_ifix:
  <<: *sql_common
  table_name: governance.metrics_stage_ifix
  pk_columns: [metrics_id]

metrics_stage_infomoney:
  <<: *sql_common
  table_name: governance.metrics_stage_infomoney
  pk_columns: [metrics_id]

metrics_stage_valorinveste:
  <<: *sql_common
  table_name: governance.metrics_stage_valorinveste
  pk_columns: [metrics_id]

metrics_stage_seudinheiro:
  <<: *sql_common
  table_name: governance.metrics_stage_seudinheiro
  pk_columns: [metrics_id]

metrics_stage_moneytimes:
  <<: *sql_common
  table_name: governance.metrics_stage_moneytimes
  pk_columns: [metrics_id]

data_quality_report:
  <<: *sql_common
  table_name: governance.data_quality_report
  pk_columns: [metrics_id]


# =============================================================================
# 01 - Stage
# =============================================================================

stage_cds:
  <<: *sql_common
  table_name: stage.stage_cds
  pk_columns: [dat_ref]

stage_ibov:
  <<: *sql_common
  table_name: stage.stage_ibov
  pk_columns: [dat_ref]

stage_ivvb:
  <<: *sql_common
  table_name: stage.stage_ivvb
  pk_columns: [dat_ref]

stage_ifix:
  <<: *sql_common
  table_name: stage.stage_ifix
  pk_columns: [dat_ref]

stage_infomoney:
  <<: *sql_common
  table_name: stage.stage_infomoney
  pk_columns: [id_news]

stage_valorinveste:
  <<: *sql_common
  table_name: stage.stage_valorinveste
  pk_columns: [id_news]

stage_seudinheiro:
  <<: *sql_common
  table_name: stage.stage_seudinheiro
  pk_columns: [id_news]

stage_moneytimes:
  <<: *sql_common
  table_name: stage.stage_moneytimes
  pk_columns: [id_news]


# =============================================================================
# 02 - Curated
# =============================================================================

# fatos:
fato_transacao_mercado:
  <<: *sql_common
  table_name: curated.fato_transacao_mercado
  pk_columns: [dat_ref, cod_indice]

fato_transacao_noticias:
  <<: *sql_common
  table_name: curated.fato_transacao_noticias
  pk_columns: [id_noticia]

fato_indice_ismb:
  <<: *sql_common
  table_name: curated.fato_indice_ismb
  pk_columns: [dat_ref]

# dimensões:
dim_indice:
  <<: *sql_common
  table_name: curated.dim_indice
  pk_columns: [sk_indice]

dim_tempo:
  <<: *sql_common
  table_name: curated.dim_tempo
  pk_columns: [sk_tempo]

dim_indicador:
  <<: *sql_common
  table_name: curated.dim_indicador
  pk_columns: [sk_indicador]

dim_fonte_noticia:
  <<: *sql_common
  table_name: curated.dim_fonte_noticia
  pk_columns: [sk_fonte]


# =============================================================================
# 03 - Indicadores
# =============================================================================

indicador_risco_credito:
  <<: *sql_common
  table_name: indicators.indicador_risco_credito
  pk_columns: [dat_ref]

indicador_retorno_mercado:
  <<: *sql_common
  table_name: indicators.indicador_retorno_mercado
  pk_columns: [dat_ref]

indicador_volatilidade_mercado:
  <<: *sql_common
  table_name: indicators.indicador_volatilidade_mercado
  pk_columns: [dat_ref]

indicador_atividade_mercado:
  <<: *sql_common
  table_name: indicators.indicador_atividade_mercado
  pk_columns: [dat_ref]

indicador_confianca_mercado_local:
  <<: *sql_common
  table_name: indicators.indicador_confianca_mercado_local
  pk_columns: [dat_ref]

indicador_sentimento_noticias:
  <<: *sql_common
  table_name: indicators.indicador_sentimento_noticias
  pk_columns: [dat_ref]


# =============================================================================
# 04 - Analytics
# =============================================================================

analytics_dashboard_diario:
  <<: *sql_common
  table_name: analytics.analytics_dashboard_diario
  pk_columns: [cod_indice, dat_ref]

analytics_serie_temporal_ismb:
  <<: *sql_common
  table_name: analytics.analytics_serie_temporal_ismb
  pk_columns: [dat_ref]

analytics_correlacao:
  <<: *sql_common
  table_name: analytics.analytics_correlacao
  pk_columns: [idx_a, idx_b, dat_ref]

analytics_kpis_agregados:
  <<: *sql_common
  table_name: analytics.analytics_kpis_agregados
  pk_columns: [entity_type, entity_name, year]
